### ISSUE TITLE
Top Half scoring False still shows teams with more w/l than games played

### ISSUE THREAD

**Issue by SrWildman** [dtcarls/fantasy_football_chat_bot#100]
**Describe the bug**
I have TOP_HALF_SCORING set to False, however my standings are still outputting teams as 2-0 and 1-1 after week one.

**Comment by dtcarls** [comment]
Just tested this and this is indeed a bug that I will address. You can delete the entire variable as a workaround until a fix is implemented.

**Comment by dtcarls** [comment]
As a follow up I will be doing the fix for all boolean variables as I'm sure this applies there as well.
