### ISSUE TITLE
Current Standings

### ISSUE THREAD

**Issue by iprva** [dtcarls/fantasy_football_chat_bot#106]
The records on the current standings output are incorrect as it shows teams played different amount of games and the wins and losses are not equal to the number of weeks played this season.

![0DA8FB42-C8B9-4887-83F0-7D5A2DB89B4B](https://user-images.githubusercontent.com/68386172/135272589-cd63644f-71a4-42e2-9a1d-e7fe79769267.jpeg)

**Comment by dtcarls** [comment]
TOP_HALF_SCORING: If set to True, when standings are posted on Wednesday it will also include top half scoring wins
Top half wins is being in the top half of your league for points and you receive an additional "win" for it. The number in parenthesis (+1) tells you how many added wins over the season for top half wins.

**Comment by iprva** [comment]
Got it. Much appreciated!
