### ISSUE TITLE
Heroku auto deploy not working

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/fantasy_football_chat_bot#116]
After clicking the purple button and logging in, just get 3 dots for loading.

**Comment by MustardLighthouse** [comment]
This is still happening for me.

**Comment by dtcarls** [comment]
FYI: Heroku is going to stop offering free product plans and plan to start shutting down free dynos and data services November 28, 2022. I am working on an alternative.

As far as the auto deploy not working, try this direct link.
https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fdtcarls%2Ffantasy_football_chat_bot%2F

**Comment by dtcarls** [comment]
Workaround of direct link solves issue

**Comment by VoodooLobster** [comment]
> FYI: Heroku is going to stop offering free product plans and plan to start shutting down free dynos and data services November 28, 2022. I am working on an alternative.
> 
> As far as the auto deploy not working, try this direct link. https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fdtcarls%2Ffantasy_football_chat_bot%2F

Thank you I just noticed the change to Heroku and was wondering what would happen.
