### ISSUE TITLE
get_starter_counts returns the wrong count if the first matchup contains a bye

### ISSUE THREAD

**Issue by heshammourad** [dtcarls/fantasy_football_chat_bot#146]
**Describe the bug**
`get_starter_counts` returns double the amount in each position if the first matchup contains a bye

**To Reproduce**
Run the function in a league week that has a bye.

**Expected behavior**
It should return the correct amount.

**Chat application**
Would happen to all of them.

**Additional context**
https://github.com/dtcarls/fantasy_football_chat_bot/blob/3f2180dd42bafa8538da10a1975e06f489941faa/gamedaybot/espn/functionality.py#L509-L513

When the away team is all on a bye, the function doesn't return in this loop. It will instead go to the second matchup and add starters to both the `a_starters` and `h_starters`. Since now the `h_starter_count` is double the correct number and is larger than `a_starter_count` which is the correct number, it will return the double size roster.

This code will not return the correct result if the first matchup has a bye and both teams have a full roster. Instead, it's probably best to use `league.settings.position_slot_counts` which should work regardless of byes or how teams fill out their rosters.

**Comment by dtcarls** [comment]
Thank you for the PR, much simplified. Glad that data is now readily available from espn-api now. I was able to replicate bug and resolved with your PR.
