### ISSUE TITLE
2 Week playoff displays wrong summary after 1st week

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/fantasy_football_chat_bot#16]
1st week completion of 2 week playoff displays wrong summary statistics.

**Comment by dtcarls** [comment]
https://github.com/cwendt94/ff-espn-api/issues/57

**Comment by bs0l** [comment]
This just occurred for me

**Comment by mtdickey** [comment]
Related: I'm running into the error below when pulling the 2nd week of a 2-week playoff matchup:
`KeyError: 'rosterForCurrentScoringPeriod'`

**Comment by cwendt94** [comment]
Hopefully this has been fixed in the latest https://github.com/cwendt94/espn-api/releases/tag/v0.9.1

**Comment by dtcarls** [comment]
Reopen if problem persists.
