### ISSUE TITLE
Serverless Setup Boilerplate/Instructions

### ISSUE THREAD

**Issue by mikaelweave** [dtcarls/fantasy_football_chat_bot#33]
These scheduled messages seem like an ideal use case for running as scheduled, serverless function in order to minimize the amount of compute needed to run this workload. Also management would be easier as there would be no need to keep the process running.

Is there any interest in some basic scaffolding code and documentation around getting this to code to work as a scheduled Azure Function? Ideally there would be an easy deployment script (terraform, bash, powershell, whatever) that folks can run to handle the deployment.

**Comment by dtcarls** [comment]
I 100% agree it fits that architecture perfectly and debated implementing
it over the summer. However the barrier to entry then gets higher for the
casual commissioner. I am still potentially interested in doing it in
another branch just for the exercise of it and potentially pull into master
if I can get it as close as possible to the “push button” setup.

**Comment by mikaelweave** [comment]
I completed this and I'm honestly not super happy with how Azure Functions requires function folders to be top level (it clutters the repository). There is a more elegant way to use a Logic App to trigger the function via HTTP but I'm out of time today and I want to think on it.

Check it out below if you'd like, it's working for my league. I can clean it up and add deployment instructions if you're looking to use it as an example in docs. Perhaps it would be more useful if I just made an Azure Function shim for this in a completely separate repo.

[Repo link here](https://github.com/mikaelweave/fantasy_football_chat_bot)

**Comment by dtcarls** [comment]
Thank you for sharing this. Do you mind if I put in a branch of this base repo?

**Comment by mikaelweave** [comment]
Not at all - I guess fixes could be merged from main back to the "cloud" branch. I have a bit of cleanup (ARM template deploy, docs) to do - but you can add it now if you'd like and I can do a PR against the new branch.

**Comment by dtcarls** [comment]
Added to azure-serverless branch. Thank you @mikaelweave
