### ISSUE TITLE
Heroku link broken?

### ISSUE THREAD

**Issue by kniq86** [dtcarls/fantasy_football_chat_bot#36]
Clicking the purple button brings me to a page on heroku that just states:

"No app.json located in the repo URL provided.

Make sure that an app.json file exists in the project root directory."

**Comment by dtcarls** [comment]
Do you have a heroku account and currently logged in?

**Comment by kniq86** [comment]
Yessir

**Comment by jcadig1** [comment]
Try clicking the purple heroku button further down the page below the discord/slack/groupme setup.

**Comment by kniq86** [comment]
Oh, hm, I was going off the modified readme link from 14 days ago which was giving me the error. just scrolling down to the readme from the main code page made the heroku buttons work. Not sure what's going on there, but I think I've got it sorted out now, thanks!

**Comment by dtcarls** [comment]
I will look into it and make sure both buttons make the correct references.

**Comment by landonp1203** [comment]
My bot does the same thing for some users, and some users do not see the issue at all.  It seems to be an issue with Heroku itself.  You can give people this link if that button is not working: https://heroku.com/deploy?template=https://github.com/dtcarls/fantasy_football_chat_bot and this looks to work.

**Comment by dtcarls** [comment]
Thank you @landonp1203
