### ISSUE TITLE
Config Problem

### ISSUE THREAD

**Issue by lemvp08** [dtcarls/fantasy_football_chat_bot#41]
After I followed the config setup in the instructions I went to resources to turn on the bot but there was a message "This app has no process yet" did I miss something in the instructions?

**Comment by dtcarls** [comment]
Did you deploy it with the purple button in the readme?

**Comment by lemvp08** [comment]
When I clicked the purple button I got this message, "No app.json located in the repo URL provided."

**Comment by dtcarls** [comment]
https://github.com/dtcarls/fantasy_football_chat_bot/issues/36

**Comment by lemvp08** [comment]
The link in #36 works. Thanks!
