### ISSUE TITLE
Scoreboard is reflecting thursday scores on each score update

### ISSUE THREAD

**Issue by jjordan1417** [dtcarls/fantasy_football_chat_bot#42]
Scoreboard is reflecting thursday scores on each score update

**Comment by dtcarls** [comment]
Are you running the latest version?

**Comment by jjordan1417** [comment]
How do i check what version i’m running?

**Comment by HennDev** [comment]
Same problem in my implementation

**Comment by dtcarls** [comment]
I would request that you try to redeploy as the latest ff-espn-api is 1.1.0 while your deploy log is 1.0.12 . A recent change to the API has a new location (scoreboard to box_score) for certain statistics may have caused the issue.

**Comment by Voidbringers** [comment]
Having the same issue too. Two bot score updates today and they both showed the Thursday scores. Checked the build log in Heroku and it says:

> Running setup.py install for ff-espn-api: finished with status 'done'
       Successfully installed apscheduler-3.6.1 certifi-2019.6.16 chardet-3.0.4 ff-espn-api-1.1.0 ...

> 

So looks like I'm running the latest version right?

**Comment by csabatini** [comment]
I had the same issue and after rebuilding the docker image from the latest changes merged into master, the score update includes Sunday.

One of the matchups has an incorrect score (maybe a separate issue) but the rest all are correct.

**Comment by dtcarls** [comment]
@csabatini can you create a separate issue and provide relevant information for having an incorrect score? Honestly, I am usually just looking at my score, so it's possible another match up may be wrong, though unlikely.

**Comment by dtcarls** [comment]
Closing issue as it didn't occur over the weekend with latest version. Reopen if problem re-occurs
