### ISSUE TITLE
Score update has inflated scores for a matchup

### ISSUE THREAD

**Issue by csabatini** [dtcarls/fantasy_football_chat_bot#44]
**Describe the bug**
Score update has scores for a matchup that are too high for both teams.

**Screenshots**
Message text  copied from Slack:
```
Actual Score Update
SHIT 123.16 - 53.16 8==D
SABA 50.56 - 61.34 WALK
HELP 99.50 - 103.62 CUT
TRM 153.38 - 67.70 BOMB
BURN 118.72 - 102.34 DEAD
Free 135.54 - 95.20 ROMO
BERB 118.62 - 49.92 MEAT
```

From ESPN app, the third score should be: **HELP 86.5 - 88.6 CUT**

**Chat application**
Slack

**Additional context**
```
LEAGUE_ID=14434
SWID=D2B41879-14A0-47CC (modified to keep information private)
ESPN_S2=AEArqDpgkK5KQaO2 (modified to keep information private)
```

**Comment by csabatini** [comment]
Fractional part of the score looks correct but one is offset by 13 points and the other by 15 points

**Comment by csabatini** [comment]
When I use ff_espn_id for my league and look at `league.box_scores(1)[2].home_score` and `away_score`, they look right (86.5 and 88.62). I'm not sure if there are any other steps that would be adding points to this?

![1568052692429](https://user-images.githubusercontent.com/3103604/64555865-dd240a00-d303-11e9-8efb-473d7ff3dec2.jpg)

**Comment by csabatini** [comment]
I see the scoreboard method is pretty much a straight pull from the API data. Maybe ESPN was bugged at that moment?

**Comment by dtcarls** [comment]
Certainly possible. ESPN was very buggy over the weekend with some week 1 stuff. Let me know if it continues

**Comment by dtcarls** [comment]
Seems to be happening even with latest version in some leagues. See https://github.com/dtcarls/fantasy_football_chat_bot/issues/45 

This will be very difficult to troubleshoot while a game is in progress. If the problem persists, can you provide your league id. If your league is not public please provide a screenshot of the full lineups (with bench) of the teams that have reported and inflated score and the incorrect corresponding message.

**Comment by csabatini** [comment]
Sounds good. Close scores message from tonight also showed the same inflated scores for the matchup above.

I'm curious if the final score update tomorrow morning will be accurate, if not I will post the details.

**Comment by dtcarls** [comment]
Opened issue with upstream library (above)

**Comment by dtcarls** [comment]
Closing as upstream issue was closed. Reopen if problem persists.
