### ISSUE TITLE
Actual Score Update -- Friday AM Shows LW

### ISSUE THREAD

**Issue by Carbja23** [dtcarls/fantasy_football_chat_bot#48]
**Describe the bug**
Actual Score Update (7:30AM EST) update is last week's scores.

**Expected behavior**
Should show only scores from the Thursday Night Game

**Comment by bs0l** [comment]
Having the same issue

**Comment by HennDev** [comment]
I'm seeing the same thing. I think this is related to the get_current_week() function, I think like 102ish. 


Since it's only look at a single team's score, if that team doesn't have anyone on Thursday, it deduces nobody has a score and it's a "future week".

**Comment by dtcarls** [comment]
Thinking the same thing. Not sure why it would've worked last year. Working
to fix.

**Comment by HennDev** [comment]
I blame ESPNs horrible design!

**Comment by foobartles** [comment]
https://github.com/dtcarls/fantasy_football_chat_bot/issues/47 

I imagine this issue is also being caused by the same thing. I think the problem code is coming from the league.scoreboard() call

**Comment by ZachMyers3** [comment]
Submitted a PR to fix the issue [#49](https://github.com/dtcarls/fantasy_football_chat_bot/pull/49).

**Comment by dtcarls** [comment]
Potentially fixed with latest merges. Leaving ticket open for a week for verification

**Comment by nez-the-old** [comment]
dtcarls your merge fix filter down to us peons automatically or do we have to reinstall the bot?

**Comment by dtcarls** [comment]
Unfortunately you have to reinstall. A lot of bugs this year with the new
API and even bugs with ESPNs data. Hopefully this is the last of the major
ones.

**Comment by nez-the-old** [comment]
Hey man no worries! I appreciate you supporting this fun bot!

**Comment by dtcarls** [comment]
Closing issue as it didn't occur over the weekend with latest version. Reopen if problem re-occurs
