### ISSUE TITLE
Projected scores incorrect when player scores 0

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/fantasy_football_chat_bot#51]
**Describe the bug**
When a player is projected to score more than 0 but then scores 0 the projection overrides the actual score.

**To Reproduce**
OJ Howard week 2

**Expected behavior**
After a game has ended if the player remains with 0 points, use that instead of projected.

**Comment by dtcarls** [comment]
watching https://github.com/cwendt94/ff-espn-api/issues/44

**Comment by cwendt94** [comment]
In ff_espn_api version 1.1.4 I added a field in box_player called “game_played”. If they haven’t played yet that value will be 0 if they are done paying the value will be 100. 

I would keep this 1.1.4 change in develop branch for a week just to make sure nothing else broke. A decent amount of logic has been added to box_scores endpoint.

**Comment by nmpeterson** [comment]
Was this tested this week? Rams defense scored 0 for me this week and the projected score update still credited them with the original projection.

**Comment by dtcarls** [comment]
It has not been integrated or tested yet. It will likely go through beta
this coming week.

**Comment by dtcarls** [comment]
In beta this week in the the develop branch

**Comment by dtcarls** [comment]
Worked over the weekend. Will merge into master once I validate https://github.com/dtcarls/fantasy_football_chat_bot/issues/62 tonight.
