### ISSUE TITLE
Both Sunday score updates displaying last week's matchups/scores on Discord

### ISSUE THREAD

**Issue by Kruser727** [dtcarls/fantasy_football_chat_bot#52]
Discord message:
https://i.imgur.com/togrhXc.png?1

This week's actual scores/matchups on ESPN:
https://i.imgur.com/JFqkzZp.png?1
https://i.imgur.com/OPsJTam.png?1

**Comment by dtcarls** [comment]
https://github.com/dtcarls/fantasy_football_chat_bot/issues/48

**Comment by Kruser727** [comment]
So, according to the thread you linked, you've already applied the fix. I just need to reinstall the program on Heroku from the start?

**Comment by dtcarls** [comment]
Yes
