### ISSUE TITLE
Bot not posting beyond week one.  

### ISSUE THREAD

**Issue by scuba-fan** [dtcarls/fantasy_football_chat_bot#53]
**Describe the bug**
It's week two of the season and the BOT is posting week one scores still

**To Reproduce**
Load the bot and let it run

**Expected behavior**
Scores should always be current.

**Screenshots**
![image](https://user-images.githubusercontent.com/18339721/64976594-8c159800-d866-11e9-93f1-ce809ff14ffb.png)

**Chat application**
SLACK

**Additional context**

**Comment by dtcarls** [comment]
This was fixed in latest update.
https://github.com/dtcarls/fantasy_football_chat_bot/issues/48
https://github.com/dtcarls/fantasy_football_chat_bot/issues/47
https://github.com/dtcarls/fantasy_football_chat_bot/issues/52
