### ISSUE TITLE
ESPN scores are displaying 0.00

### ISSUE THREAD

**Issue by OHbuckeyeIO** [dtcarls/fantasy_football_chat_bot#54]
**Describe the bug**
When the message for updated scores went out on Monday they were all 0 points. (See attached image)

**To Reproduce**
Have teams score points and then have the bot send the score update

**Expected behavior**
Expected an updated scoreboard with up-to-date football scores as reflected in ESPN

**Screenshots**
![GM ESPN Bot](https://user-images.githubusercontent.com/55416491/64999753-8e9be000-d8ae-11e9-9959-72b8b3dfe1e3.JPG)

**Chat application**
GroupMe

**Additional context**

**Comment by dtcarls** [comment]
Have you installed the latest version (within the last 3 days)? If not please do and verify the bug is still occurring.

**Comment by OHbuckeyeIO** [comment]
No, I am sorry, I'm well-versed in this kind of technological setup. How do I do that? I followed the following instructions, which seems to have worked, except for the "0.00" scores. 

Thanks!

**Comment by OHbuckeyeIO** [comment]
* https://github.com/dtcarls/fantasy_football_chat_bot#setting-up-groupme-discord-or-slack-and-deploying-app-in-heroku
