### ISSUE TITLE
Don't send close scores of games with no players playing Monday night

### ISSUE THREAD

**Issue by foobartles** [dtcarls/fantasy_football_chat_bot#62]
**Is your feature request related to a problem? Please describe.**
It is frustrating when the bot sends close scores of teams that have no players playing in the Monday night game.

**Describe the solution you'd like**
Check the rosters of games with close scores for active players. Ideally the bot would only send close scores of games where the team that is behind has an active player in.

**Comment by cwendt94** [comment]
I am almost done adding a feature to [ff_espn_api](https://github.com/cwendt94/ff-espn-api) where the players will have a field if there done playing or not. This can be used to fix this issue.

**Comment by dtcarls** [comment]
In beta this week in the the develop branch
