### ISSUE TITLE
Power Rankings message did not send

### ISSUE THREAD

**Issue by Steverock6** [dtcarls/fantasy_football_chat_bot#63]
Reinstalled new version on 9/22/2019. 
 9/24/19 morning trophy message worked. No changes were made to Heroku or Groupme after this point.

Both bots ( I utilize two of them ) did not send power ranking messages.

**Comment by dtcarls** [comment]
My power rankings have run fine in multiple leagues. 
Are you out of Heroku hours? My suspicion is that since you are running two, you might be out of free hours without credit card linked. You should have received an email at 80% utilization and 100% utilization of free hours.

**Comment by dtcarls** [comment]
This issue will close on Monday (9/30) unless you report that the problem persists and provide more logging.
