### ISSUE TITLE
Private league access denied despite SWID and espn_s2 present

### ISSUE THREAD

**Issue by scmarlatt** [dtcarls/fantasy_football_chat_bot#64]
Hey, I have everything almost up and running on Heroku, but for some reason, I'm getting access denied when starting up.

I'm able to run it locally and see my test message coming in just fine. I believe all of my environment variables are the exact same. I've triple checked this.

Any ideas?

**Comment by scmarlatt** [comment]
I think this is because the League constructor now expects arguments by keyword. Changes were made just a few days ago which you can find [here](https://github.com/cwendt94/ff-espn-api/commit/74da3241ec024d8f2876ab6b24e02690c77b4283)

**Comment by dtcarls** [comment]
Thank you for catching that. I'll patch it today. However the change you
linked is not yet in master in this repo, but is in develop. Which branch
are you having issues with?

**Comment by cwendt94** [comment]
I didn't catch that. I could just put those new parameters at the end of the League constructor so it doesn't break anything

**Comment by dtcarls** [comment]
No worries. I like the current implementation I'll just make the quick mod
to fix it
