### ISSUE TITLE
Trophies of the Week gives "barely beat" descriptor to ties 

### ISSUE THREAD

**Issue by KellenInfoTech** [dtcarls/fantasy_football_chat_bot#67]
When a match is tied, the Trophies of the Week section of the final score update says

"team1 barely beat team 2 by a margin of 0.00"

**To Reproduce**
A team ties

**Expected behavior**
To show that the closes match was a tie, rather than describe one team as beating the other

**Screenshots**
![image](https://user-images.githubusercontent.com/54373402/67288369-d82dab00-f4aa-11e9-83f7-0e218fb5418c.png)

**Chat application**
slack

**Additional context**

**Comment by dtcarls** [comment]
Would it be acceptable for the tie to be ignored and return the next closest game?

**Comment by KellenInfoTech** [comment]
That sounds like reasonable behavior to me.
