### ISSUE TITLE
2020 Leagues

### ISSUE THREAD

**Issue by dustin25ship** [dtcarls/fantasy_football_chat_bot#69]
Any update for 2020 Leagues? This doesn't seem to be working anymore, perhaps due to the ESPN layout change. Trying this with a 2020 baseball league, but no luck.

**Comment by dtcarls** [comment]
There are plans to get this working for the 2020 season. It has never officially worked for baseball and only has support for football at this time.

**Comment by conormaloney2330** [comment]
Echoing above the desire to have this for the 2020 season! Curious if there is any ETA you could provide? Thanks @dtcarls !

**Comment by Xpunker1** [comment]
Any ETA on when this will be updated for 2020 season?

**Comment by dtcarls** [comment]
I'm glad everyone is anxiously awaiting. I am working on it. Will be done this week.
