### ISSUE TITLE
League Activity

### ISSUE THREAD

**Issue by marcopollo89** [dtcarls/fantasy_football_chat_bot#71]
Would love to see an optional addition for league activity. Specifically added/dropped players.
Also pulling from the league activity - would like to be able to pull team name changes. Currently manually changing nicknames in Discord to match team names in the league.

**Comment by dtcarls** [comment]
Looking into implementing add/drops. Maybe on a daily summary basis as real time could get a bit spammy.

**Comment by GingaVitis** [comment]
This would be awesome, but more-so I'd love to get notified when waivers clear as well.

**Comment by dtcarls** [comment]
ESPN currently doesn't allow the API to retrieve the activity without authentication. Blocked until a solution is found

**Comment by TheSirLancelot** [comment]
Would this work for private leagues? And/or has there been a solution identified?

**Comment by dtcarls** [comment]
It will work for a private league or a public league with private league variables populated. Currently being worked.

**Comment by TheSirLancelot** [comment]
I'm interested in helping out with this, but won't be able to work on it until next week. How close are you to getting it implemented? I won't worry about it if you're almost there..

**Comment by dtcarls** [comment]
I've been swamped at work so haven't worked on it enough. This branch https://github.com/dtcarls/fantasy_football_chat_bot/tree/sdvgallardo is up to date with the latest changes. Hope to have it ready by Wednesday waiver run in develop branch.

**Comment by dtcarls** [comment]
Feature is in the develop branch for beta release. If no bugs over the next week, I'll merge to master. Currently it will only run on wednesday mornings and only display waiver claims.

**Comment by TheSirLancelot** [comment]
Hmm, just took a look at the develop branch, but it seems like the waiver report schedule is commented out

**Comment by dtcarls** [comment]
It is sent out with the standings message. Wednesday at 7:30am local. https://github.com/dtcarls/fantasy_football_chat_bot/blob/develop/ff_bot/ff_bot.py#L554
