### ISSUE TITLE
Deploy button on the Readme doesn't seem to be working

### ISSUE THREAD

**Issue by danigle** [dtcarls/fantasy_football_chat_bot#80]
Sorry if this doesn't belong here. I'm probably doing something wrong, but when I click the Heroku Deploy button, it just sends me to the Heroku login page, even when I'm already logged in. 

I feel like when I clicked the button previously, it would open up a deploy window on Heroku.

**Comment by danigle** [comment]
I should clarify. I am not able to deploy the app via the Deploy button.

**Comment by dtcarls** [comment]
Some people have reported issues hitting the purple "Deploy to Heroku" button on their desktop, others from their phone, and most work fine. Really inconsistent and I've been unable to pinpoint the underlying cause of the issue. Try a different computer/phone/browser when hitting the button in the readme. Any information you could provide to help me find the problem would be helpful.

**Comment by danigle** [comment]
I'm not sure what the difference was, but I let Heroku/GitHub have a little timeout. I tried today and it worked like a champ.

Thanks again @dtcarls for this awesome bot. We're loving it.
