### ISSUE TITLE
get_projected_total is incorrectly adding projected scores from players on IR

### ISSUE THREAD

**Issue by sdvgallardo** [dtcarls/fantasy_football_chat_bot#83]
**Describe the bug**
This function takes players that are on the bench ('BE') and throws their projections out, but not players on IR. 

**To Reproduce**
This week, look at any team that had Sterling Shepard on IR. His score was added to their projections. He was a last minute activation and ended up gaining points in the game. 

**Expected behavior**
IR players' scores should not be included in projected totals.

**Comment by dtcarls** [comment]
I'll take a look this weekend. Thank you, this is not a situation I had anticipated.
