### ISSUE TITLE
Get projected scores

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/fantasy_football_chat_bot#9]
Will need to scrape HTML to get projected scores.

**Comment by dtcarls** [comment]
Yes. I also think near “real time” is a wanted feature

**Comment by dtcarls** [comment]
Yes. So my plan was that when a score update is given I would also give the
projected score along side as an indicator of how much the score actually
matters.

**Comment by dtcarls** [comment]
That would be awesome

**Comment by cwendt94** [comment]
So I forgot you can use box_scores() function in ff_espn_api to get projected scores. It will return a list of Box Score match ups with home and away team rosters with projected and actual points. I believe it will update as the games play on. Check out get box score section in [ff-espn-api](https://github.com/cwendt94/ff-espn-api) README

**Comment by dtcarls** [comment]
In beta in develop branch https://github.com/dtcarls/fantasy_football_chat_bot/commit/499f71b6dd3adb65b9b2e0750abf2a76e6d97d93

**Comment by dtcarls** [comment]
Projected scores were also reporting bench players. Fixed in https://github.com/dtcarls/fantasy_football_chat_bot/commit/8d9cc138d0ce30400ab19400f63a28f583eb38e7 Still in beta in develop branch until 1 week of accurate projections.

**Comment by dazayas** [comment]
It seems the projected scores in box_scores() don't update in real time as the games play on or after they're final.  If a player underperforms, their larger projection is still factored in.  I suppose one could replace the projection with the actual score, if actual >0, but that will lead to very low projections during gameplay.  Is there a way to scrape the team's projected score elsewhere in the espn API?

**Comment by dtcarls** [comment]
The >0 approach is what I went with for now. I will try to see how the new fastasycast retrieves the real time projection scores as well as how it attempts to calculate "win percentage" during today's games

**Comment by dtcarls** [comment]
Put this into master. Live data is being pulled in via a websocket connection and not accessible via API as far as I can tell. Projections are approximate, but gets the point across.
