### ISSUE TITLE
Is this app still working??

### ISSUE THREAD

**Issue by rylertego** [dtcarls/fantasy_football_chat_bot#91]
Was just wondering if this is still functioning

**Comment by dtcarls** [comment]
I haven't yet tested it for this coming league year, but yes I intend on making it work.

**Comment by mareinma** [comment]
i followed the instructions to set up and set up an account with heroku, but i couldnt confirm because "This app has no process types yet". is there an easy fix to this? im new to all of it

**Comment by mareinma** [comment]
> i followed the instructions to set up and set up an account with heroku, but i couldnt confirm because "This app has no process types yet". is there an easy fix to this? im new to all of it

Nevermind! I got it to work.

**Comment by dtcarls** [comment]
Latest version just pushed to master to work for 2021 season.
