### ISSUE TITLE
Current standings posting on wrong day

### ISSUE THREAD

**Issue by agzhaoagzhao** [dtcarls/fantasy_football_chat_bot#96]
**Describe the bug**
Current standings posting on wrong day

**To Reproduce**
Not sure how to reproduce --- the Current Standings were posted Weds morning instead of Tues morning. 

**Expected behavior**
Should post on Tuesday.

**Screenshots**
![image](https://user-images.githubusercontent.com/89935175/131717217-fdc2149c-1502-4924-9e3c-cfcac0cff0d7.png) note Sept 1 2021 is a Wednesday

**Chat application**
Discord

**Adtl**
I'm not a coder

**Comment by dtcarls** [comment]
Wednesday is the correct day and is in the code as such. The reasoning behind Wednesday instead of Tuesday is to allow for stat corrections. I will correct the readme to reflect the correct day.

**Comment by agzhaoagzhao** [comment]
Thank you!
